### ISSUE TITLE
Launch checklist

### ISSUE THREAD

**Issue by jplhomer** [jplhomer/site-next#2]
- [x] Sitemap/RSS/JSON feeds
- [x] Favicon
- [x] Footer links (Email, RSS/JSON, YouTube maybe)
- [x] creative.jplhomer.org redirects
- [x] About page
- [x] Responsive nav
- [x] Disable mobile hover overlay on Glances
- [x] Newsletter
